### ISSUE TITLE
Conflict with AsReadOnly() extensions

### ISSUE THREAD

**Issue by eladmarg** [NightOwl888/J2N#91]
Because newer .net core version has the extension AsReadOnly(), there is a conflict between this extension.

my suggestion is to add #IF_FLAG for the compiler to avoid this conflict.
(this detected as part of targeting lucenenet to 8.0)

**Comment by NightOwl888** [comment]
Yeah, looks like we will need to target `net8.0` to avoid this. Can you be more specific as to which types you are seeing this in?

**Comment by eladmarg** [comment]
> Yeah, looks like we will need to target `net8.0` to avoid this. Can you be more specific as to which types you are seeing this in?

Mostly at the Dictionary and List

**Comment by NightOwl888** [comment]
Added task #93.
